# Pipeline CI para projeto .NET Core
# Compila, testa e publica a aplicação ASP.NET Core
trigger:
- main  # ou o nome do seu branch principal (ex: master)

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '8.0.x'

steps:
# 1️⃣ Instalar SDK do .NET
- task: UseDotNet@2
  displayName: 'Instalar .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '$(dotnetVersion)'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# 2️⃣ Restaurar pacotes
- script: dotnet restore
  displayName: 'Restaurar pacotes NuGet'

# 3️⃣ Compilar o projeto
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Compilar projeto'

# 4️⃣ Executar testes (se tiver)
- script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Executar testes automatizados'
  continueOnError: true  # permite continuar mesmo que não haja testes

# 5️⃣ Publicar aplicação (gera arquivos prontos pra deploy)
- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publicar aplicação'

# 6️⃣ Publicar artefatos no Azure DevOps
- task: PublishBuildArtifacts@1
  displayName: 'Publicar artefatos de build'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
